export type ColorScheme = typeof Colors.light;

export const Colors = {
  light: {
    background: '#EFF6FF',
    surface: '#FFFFFF',
    surfaceAlt: '#E2EFFC',
    surfaceDeep: '#D0E8F7',
    primary: '#5BB8D4',
    primaryLight: '#88CEDF',
    primaryDark: '#3A9DBB',
    secondary: '#A0CFEA',
    accent: '#FFD97D',
    accentDeep: '#F5B731',
    lavender: '#DEC8F8',
    lavenderDeep: '#B48DE8',
    navy: '#0F2744',
    text: '#1A3350',
    textMuted: '#4A6A85',
    textLight: '#6E92AB',
    border: '#C2DFEE',
    borderLight: '#DCF0FA',
    shadow: 'rgba(91, 184, 212, 0.20)',
    shadowDeep: 'rgba(15, 39, 68, 0.12)',
    tabBar: '#FFFFFF',
    tabBarActive: '#5BB8D4',
    tabBarInactive: '#7FA8C0',
    error: '#E8706A',
    errorLight: '#FDECEA',
    success: '#5DB87A',
    successLight: '#E2F5E8',
    moodColors: {
      happy:      '#FFE599',
      sad:        '#A8C8F0',
      angry:      '#F5B8BE',
      anxious:    '#CAB8F0',
      calm:       '#8ED8C0',
      excited:    '#FFC878',
      tired:      '#B8C8D8',
      grateful:   '#F5D890',
      melancholy: '#AAC0D8',
      hopeful:    '#A8E0BC',
    } as Record<string, string>,
    radius: 20,
    radiusSm: 12,
    radiusLg: 28,
    radiusXl: 36,
  },
};
