export type ColorScheme = typeof Colors.light;

export const Colors = {
  light: {
    background: '#F0F8FF',
    surface: '#FFFFFF',
    surfaceAlt: '#E8F4FD',
    surfaceDeep: '#DCF0FA',
    primary: '#7EC8E3',
    primaryLight: '#A8DBF0',
    primaryDark: '#5AABCC',
    secondary: '#B8E0F0',
    accent: '#FFE4A0',
    accentDeep: '#FFCA6B',
    lavender: '#E8D5F5',
    lavenderDeep: '#C9AEED',
    navy: '#1A3A5C',
    text: '#2C4A6E',
    textMuted: '#7A9DB5',
    textLight: '#A8C4D8',
    border: '#D4EAF7',
    borderLight: '#EDF6FD',
    shadow: 'rgba(126, 200, 227, 0.18)',
    shadowDeep: 'rgba(26, 58, 92, 0.10)',
    tabBar: '#FFFFFF',
    tabBarActive: '#7EC8E3',
    tabBarInactive: '#A8C4D8',
    error: '#F28B82',
    errorLight: '#FDECEA',
    success: '#98D4A3',
    successLight: '#E8F5E9',
    moodColors: {
      happy: '#FFE4A0',
      sad: '#B8D4F0',
      angry: '#F5C2C7',
      anxious: '#DDD0F0',
      calm: '#A8E0D0',
      excited: '#FFD4A8',
      tired: '#D0D8E4',
      grateful: '#F5E6A8',
      melancholy: '#C8D8E8',
      hopeful: '#C8ECD8',
    } as Record<string, string>,
    radius: 20,
    radiusSm: 12,
    radiusLg: 28,
    radiusXl: 36,
  },
};
